### ISSUE TITLE
Issue with Vers 6.2.5

### ISSUE THREAD

**Issue by MrBlockchain22** [XDCFoundation/XDCPay#4]
XDCPay opens the window to submit payment for the transaction but the popup is blank. The only way to make it work is to open the wallet again and hit submit on that window.  This happened with claiming rewards on the SRX website and also while testing our new dapp for minting XRC20 tokens.  

**To Reproduce**
1. Go to our minting token website 
2. Go through the process of creating the token and to finalize the transaction, hit submit.  
3. XDCPay will open up a pop window that should prompt you to pay for the transaction but it remains blank and the XDCPay wallet will have a number 1 on it (representing a pending transaction). If you click on the XDCPay wallet, you will see the submit button to pay for the transaction.
4. The issue is that the popup window should be available to click submit to pay for the transaction but it hangs and it remains blank.

**Comment by Prashant160792** [comment]
@MrBlockchain22 We are able to replicate this issue at our end and we are working on it in the new version. We will keep you posted once fixed.

**Comment by Prashant160792** [comment]
@MrBlockchain22 We have fixed this issue. You will be able to see this in the new release.

**Comment by WalterBlueu** [comment]
Issue resolved with XDCPay v6.2.7
