### ISSUE TITLE
Explorer link bug

### ISSUE THREAD

**Issue by davemarc86** [XDCFoundation/XDCPay#5]
I created a custom token (Walter Blueu created it for me, as part of what he was doing on Twitter). He sent the token to my XDCPay wallet. When I clicked on my token and "view in block explorer", it sends me to this link: https://explorer.xinfin.network/token/xdcaa41a562db79cc9ebf55cfe862344521fc5f8e9a

The link doesn't work. Weirdly enough it did at first, but stopped working.

However, when you change "token" in the above link to "address" it works. As shown: https://explorer.xinfin.network/address/xdcaa41a562db79cc9ebf55cfe862344521fc5f8e9a

This is a small issue but may make a lot of people think their coin doesn't exist on the chain if it's not linking to the right place in the explorer. I needed help to figure it out.

**Comment by Prashant160792** [comment]
@davemarc86 There might be some issue with the explorer that it was not loading. We tried to replicate this at our end by adding the same token using the address and it is working fine now.

Can you please check and let me know if you are still facing the same issue?

This is related to live XDC explorer where it is not loading the token details page, not to the XDCPay.

If not then please close this bug.

**Comment by WalterBlueu** [comment]
This issue has been resolved with XDCPay v6.2.6
