### ISSUE TITLE
XDCPay is showing 10 Quadrillion tokens when only 1 Million were created

### ISSUE THREAD

**Issue by XDCFoundation** [XDCFoundation/XDCPay#6]
**Describe the bug**
I created a new token called HEKT and minted 1M, I verified this by looking at the contract address on blocksscan.

![image](https://user-images.githubusercontent.com/87303604/151809434-01e96dd8-5f4e-4644-a3c8-5f251dc2c11d.png)

I then sent all 1M HEKT tokens to the person who requested the token creation.  However when that person views the HEKT token in their XDCPay account it is showing up as 10 Quadrillion tokens.  I had multiple people report this issue to me.

![image](https://user-images.githubusercontent.com/87303604/151809616-12da2c3d-6329-4fe8-881f-13fefc4f63a2.png)

**To Reproduce**
Add HEKT Token to your XDCPay account:

The user added HEKT token to their XDCPay account using the following information

Contract Address: xdc8e2a3ca515407d300daf19a9fb3ede0d62755060
Symbol: HEKT
Decimals: 18

Then I sent them all 1M HEKT tokens: https://explorer.xinfin.network/txs/0xe91ac564d662baeeda84ab080a9390fa9475d37a7ce19d2502224a3ab320d308

Then the user reported that XDCPay was showing that they held 10 Quadrillion HEKT

**Expected behavior**
The user should be seeing 1M HEKT in their XDCPay account.

**Browser details (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - XDCPay v6.2.4

**Comment by Prashant160792** [comment]
@XDCFoundation This issue will be resolved in the new version. In the new version, when you will add the token using the contract address then it will automatically fetch the token symbol and token decimal value and the token decimal value will not be editable.

In the live version of XDCPay, the user has to enter the contract address, token symbol and decimal value manually and he/she can enter any decimal value irrespective of the decimal value of the deployed token.

**Comment by WalterBlueu** [comment]
Issue Resolved with XDCPay v6.2.5
